trigger:
  paths:
    include:
      - Sondor.ProblemResults/**

pool:
  vmImage: ubuntu-latest

variables:
- name: major
  value: 1
- name: minor
  value: 0
- name: repository
  value: sondor-problem-result-package
- group: sondor-git
- group: sondor-nuget

resources:
  repositories:
    - repository: templates
      type: git
      name: sondor-pipeline-templates
      ref: master

steps:
- template: package-publish.yml@templates
  parameters:
    nuGetFeedType: 'external'
    repository: ${{ variables.repository }}
    feed: ''